# Qubes HUD managed file. Owner: salt/qubes_gui/guest_hud.

[Appearance]
color_scheme_path=$XDG_CONFIG_HOME/qt5ct/colors/qubes-hud.conf
custom_palette=true
icon_theme=Qubes-HUD-Cyan
standard_dialogs=default
style=Fusion
